name: Typescript Test

on:
  push:
    branches:
      - '**'

defaults:
  run:
    shell: bash

jobs:
  typescript-test:
    runs-on: ubuntu-latest

    env:
      API_HOST: localhost
      API_PORT: 8001
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: datadvisor
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: datadvisor
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: passw0rd

    services:
      postgres:
        image: postgres:14.5-alpine
        env:
          POSTGRES_USER: datadvisor
          POSTGRES_PASSWORD: passw0rd
          POSTGRES_DB: datadvisor
        ports:
          - '5432:5432'

      redis:
        image: redis:7.0.4-alpine
        env:
          REDIS_PASSWORD: passw0rd
        ports:
          - '6379:6379'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 17.x
        uses: actions/setup-node@v3
        with:
          node-version: 17.x

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests and coverage
        run: yarn test:cov

      - name: Run e2e tests
        run: yarn test:e2e
