name: Typescript Test

on:
  push:
    branches:
      - '**'

defaults:
  run:
    shell: bash

jobs:
  typescript-test:
    runs-on: ubuntu-latest

    env:
      API_HOST: localhost
      API_PORT: 8001

      POSTGRES_URL: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@postgres:5432/datadvisor?schema=api

      REDIS_URL: redis://:${{ secrets.REDIS_PASSWORD }}@redis:6379/0

      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

    services:
      postgres:
        image: postgres:14.5-alpine
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DATABASE }}

      redis:
        image: redis:7.0.4-alpine
        env:
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 17.x
        uses: actions/setup-node@v3
        with:
          node-version: 17.x

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests and coverage
        run: yarn test:cov

      - name: Run e2e tests and coverage
        run: yarn test:e2e:cov
